language: en
pipeline:
- name: WhitespaceTokenizer
  token_pattern: (?u)\b\w+\b
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: oov
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  model_confidence: softmax
  epochs: 200
  ranking_length: 5
  constrain_similarities: True
- name: DucklingEntityExtractor
  url: http://duckling.rasa.com:8000
  dimensions:
  - email
  - number
  - amount-of-money
- name: EntitySynonymMapper
- name: ResponseSelector
  constrain_similarities: True
  retrieval_intent: out_of_scope
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  constrain_similarities: True
  retrieval_intent: faq
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  constrain_similarities: True
  retrieval_intent: chitchat
  scale_loss: false
  epochs: 100
- name: FallbackClassifier
  threshold: 0.7
policies:
- name: customcomponents.custom_policy.ButtonPolicy
  button_action_name:  "action_process_button_answer"

- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True
- max_history: 6
  name: AugmentedMemoizationPolicy
- name: TEDPolicy
  constrain_similarities: True
  model_confidence: softmax
  max_history: 10
  epochs: 20
  batch_size:
  - 32
  - 64
